.github/workflows/create-branch.yml
.github/workflows/issue-autolink.yml

add basic workflows

---

.github/issue-branch.yml

add config for formatting

---

package.json
yarn.lock

Added the Pinia package as per issue #17 
Resolve #17

Issue 17: Install Pinia

---

components/Header/index.vue
components/SearchBar/index.vue
data/adjudicators.json
nuxt.config.js
package.json
pages/adjudicators.vue
tailwind.config.js
yarn.lock

- Added page route  `/adjudicators`
- Added `Header` Component - To be used on multiple pages/components
- Added `SearchBar` Component - To be used on multiple pages/components
- Installed `heroicons`
- Fixed tailwind config by putting colours in extend, this allows you to use the tailwind default colours aswell.
- Added dummy JSON data
- List adjudicators from JSON data
- Added the ability to filter by first name
- I noticed that the navbar is not fixed at the top when scrolling. I will create a new PR
- Resolve #34

I34 Create Manage Adjudicators Page

---

components/NavBar/NavBar.vue

Changed the NavBar class so that it is sticky to the top of the page
- [ x] The pull request title has an issue number
- [ x] The change works by "Smoke testing" or quick testing
- [ x] The change has tests

hotfix - navbar made sticky

---

components/Button/index.vue
components/Header/index.vue
components/SearchBar/index.vue
pages/adjudicators.vue
pages/components.vue

- Added a button component that should be used across our pages & other components
- Can pass the button text and button colour as props
- Added a component page `/components` that displays all the components (Header, Buttons, Searchbar)
- The component page  is to be removed before end of project session or until documentation is setup
- Cleaned up search bar
closes #39 
- Resolve #39

I39 Create Button Component

---

Firebase/functions/package.json

just edited the node version in the firebase folder back to when it worked
**Fill this up (NA if not available). If certain criteria are not met, can you please give a reason?**
closes #58 
- Resolve #58

revert node version

---

assets/css/main.css
components/HomePage/LevelButton.vue
nuxt.config.js

heading-montserrat class now renders. heading-jost & heading-lato renders without any fixes
- Resolve #74

I74 tailwind custom fonts not rendering

---

Firebase/README.md
Firebase/firebase.json
Firebase/firestore.indexes.json
Firebase/firestore.rules
Firebase/storage.rules
package.json

I70 add firebase security rules for user

---

components/Table/index.vue
data/tournaments.json
pages/admin/signup-requests.vue
pages/admin/tournaments.vue

Nothing too fancy, mostly just copied the admin/venue page and implemented the necessary values. 
Updated Table/index.vue to say "data" instead of "venue" to be more neutral for non-venue components
- Resolve #41 
- Resolve #41

I41 create tournament page

---

Firebase/README.md
Firebase/firestore.rules
components/SignUpForm/Roles.vue
nuxt.config.js
pages/login.vue
stores/user.js

read over the Firebase/readme.md file for up to date instructions
- Resolve #87

I87 integrate firebase into user store

---

Firebase/firestore.rules

Updated the firestore rules to now accommodate for the final database schema design 
Please refer to the firestore website to see previous versions 
- Resolve #123

i121->123-update firestore rules

---

components/SignUpForm/index.vue
pages/login.vue
stores/user.js

- Added Phone Number to Rego Form
- Fixed Styling for Login Page
- Added redirect link from login to rego page and vice versa
- Resolve #104

I104 add phone number to registration form

---

components/SearchBar/index.vue
components/Table/index.vue
components/Tabs/index.vue
components/admin/AdminButton.vue
data/users.json
pages/admin/contacts.vue
pages/admin/index.vue
pages/admin/venues.vue
pages/components.vue

- Added a tabs component, added it to the components page as well
- Loads table data based on the tab clicked
- Remove adjudicators and users from admin dashboard and replaced it with contacts
- Fixed table styling and other small styling changes
- Filters data based on first/last name and current tab
- Resolve #118

I118 Replace adjudicators and users with contacts

---

.dockerignore
Firebase/firebase.json
Firebase/functions/package-lock.json
docker-compose.yml
docker/emulator/Dockerfile

Containerize firebase emulator to simplify project setup (for those who have not installed firebase tools and dependencies and want to get started on project)
run docker-compose up && yarn dev
- Resolve #120

I120 dockerize firebase emulator

---

components/NavBar/NavBar.vue

Added button for admin users on nav bar that takes them to admin page.
- Resolve #140

I140 added admin button to nav bar

---

components/admin/ProfileInfo.vue
pages/admin/index.vue

Added top margin to profileInfo + user variable in admin page

---

pages/admin/venues.vue

- deployment failed because it could find the modal
- Resolve #169

i169 fixed deployment issue

---

components/Table.vue

I171 fix table component

---

pages/admin/contacts.vue
pages/admin/create-admin.vue
pages/admin/index.vue
pages/admin/institutions.vue
pages/admin/signup-requests.vue
pages/admin/tournaments.vue
pages/admin/venues.vue
pages/coordinator.vue
pages/coordinator/changepassword.vue
pages/coordinator/draw.vue
pages/coordinator/index.vue
pages/coordinator/institutions.vue
pages/coordinator/team-registration.vue
pages/coordinator/userinformation.vue
pages/index.vue
pages/login.vue
pages/signup.vue

- add titles to all pages
- Resolve #193

i193-add titles to all pages

---

pages/admin/institutions.vue
pages/admin/tournaments.vue
stores/institutions.js
stores/tournaments.js

- Refactored `filteredTournaments` & `filteredInstitutions` into computed properties.
- Trying to avoid closing #192
This issue is a part of #192

Fix `filteredTournaments` & `filteredInstitutions` not being cleared

---

pages/admin/index.vue

removed links on admin page to venues and contacts

---

pages/admin/institutions.vue
pages/coordinator/institutions.vue

removed school code + clarified form fields

---

components/Table.vue
pages/admin/contacts.vue
pages/admin/institutions.vue
pages/admin/tournaments.vue
pages/admin/venues.vue

- Added no data text prop to table
- Each instance of Table component either passes in no data text or uses default
- Added another div to table component with flex direction as column

Bugfix - No table data error message on same line and default text

---

components/DeleteDialog.vue
components/Modal.vue

made component width scale with screen.
- Resolve #208

I208 resized DeleteDialog component

---

stores/user.js

- fixed error codes on login and signup
- Resolve #214

i214-fixed error codes

---

pages/coordinator/team-registration.vue
stores/institutions.js

Changes to team rego:
> fixed hardcoding -- was causing a bug.
> now checks if tournament is chosen
> now checks if team is selected but 0 total chosen
> now ensures somebody cant enroll more than 50 teams of a specific division at once. 
> renamed function "registerTeam" -> "registerTeams"
> made error messages more descriptive
- Resolve #196

I196 incorrect error codes in team rego

---

stores/user.js

changed from session storage to local storage, now keeps auth on opening new tab

changed persist to local storage

---

components/Table.vue
pages/admin/contacts.vue
pages/admin/institutions.vue
pages/admin/signup-requests.vue
pages/admin/teams.vue
pages/admin/tournaments.vue
pages/admin/venues.vue
pages/coordinator/index.vue

- Added the 'Capacity' & 'Rounds' columns to the venue & tournament tables respectively 
- Refactored the table & added a slot to override the rendering of specified columns
- Fixed the table not scrolling on overflow

I230 Updated Tournament and Venue Table Columns

---

Firebase/functions/package.json
Firebase/functions/yarn.lock
package.json
plugins/1.firebase.client.js
yarn.lock

- implement analytics in the firebase init file 
- Resolve #239

I239 setup analytics

---

pages/admin/signup-requests.vue
pages/signup.vue
stores/admin.js
stores/user.js

- Added School name form field in signup page
- Added school column in signup requests page
- Resolve #282

Added school field and display in table

---

docs/docs/tournament-setup.md
docs/mkdocs.yml

- Added docs for managing a tournament
run mkdocs serve in docs folder
- Resolve #262

I262 add documentation for admin users

---

pages/admin/institutions.vue
pages/admin/tournaments/index.vue
pages/admin/venues.vue
stores/institutions.js
stores/tournaments.js
stores/venues.js

- added in the proper delete functionality to torni, insti, and venue page 
- also added warning to these actions as its quite big
- Resolve #278

I278 integrate firebase into delete buttons

---

pages/admin/contacts.vue

- add admin to contacts page 
- make team coordinator the active option on first load up
- Resolve #290

add admin, change active to team coordinator

---

data/juniorDraw.json
data/noviceDraw.json
data/seniorDraw.json
pages/fixtures/[tournamentId].vue

- Commented out fixtures loading from firebase and replaced with json data
- Resolve #294

fixtures load from JSON data

---

data/juniorDraw.json
data/noviceDraw.json
data/seniorDraw.json

More JSON changes
- Resolve #298

i298 Convert Draft Fixtures to Final Fixtures

---

components/Table.vue

- change the font around in the table component
- Resolve #303

change font to monsterat at font weight to medium/500

---

components/Table.vue
data/juniorDraw.json
data/noviceDraw.json
data/seniorDraw.json
pages/fixtures/[tournamentId].vue

- "View Topic" button which opens a modal and displays the topic
- Set max width on table
- Change fixtures data (again)
- Resolve #301

I301 the topic takes too much space

---

data/noviceDraw.json

updated novice draw
- [*] The pull request title has an issue number
- [n/a] The change works by "Smoke testing" or quick testing
- [n/a] The change has tests
- [n/a] The change has documentation
- Resolve #317

updated novicedraw.json

---

data/seniorDraw.json

updated matchups data

---

components/SearchBar.vue
pages/fixtures/[tournamentId].vue
stores/matchups.js

I329 update tournament matchups

---

pages/adjudicator/fixtures/[tournamentId].vue

- add the extra column for adjudicator so scoresheet can work
- Resolve #333

fix table problem

---

pages/scoresheet.vue
stores/admin.js

I311 create scoresheet page

---

Firebase/firestore.rules
components/Table.vue
middleware/logged-in.global.js
pages/adjudicator/[tournamentId]/index.vue
pages/adjudicator/[tournamentId]/scoresheet/[matchupId].vue
pages/adjudicator/fixtures/[tournamentId].vue
pages/adjudicator/index.vue
pages/adjudicator/scoresheet/[scoresheet].vue
pages/index.vue
stores/adjudicator.js
stores/admin.js
stores/matchups.js

- all done, works really well quite suprised, router.back way to go i reckon
- Resolve #326

I326 integrate scoreboard into adjudicator page

---

components/Table.vue
package.json
pages/adjudicator/[tournamentId]/index.vue
pages/adjudicator/[tournamentId]/scoresheet/[matchupId].vue
pages/admin/tournaments/[tournamentId]/index.vue
pages/admin/tournaments/[tournamentId]/matchups-approve.vue
pages/admin/tournaments/[tournamentId]/matchups-approve/index.vue
pages/admin/tournaments/[tournamentId]/matchups-approve/scoresheet/[matchupId].vue
pages/admin/tournaments/[tournamentId]/matchups-upload.vue
pages/fixtures/[tournamentId].vue
stores/matchups.js
yarn.lock

- lots of good stuff
- Resolve #339

I339 get admin approval on matchup scoresheet

---

package.json
pages/admin/tournaments/[tournamentId]/index.vue
pages/admin/tournaments/[tournamentId]/matchups-upload.vue
stores/matchups.js
yarn.lock

- lots of good stuff
- Resolve #336

I336 upload matchups

---

components/Division/DivisionPanel.vue
pages/admin/tournaments/[tournamentId]/division/[level].vue

I346 implement bye to development
